name: movies_app
description: an application which gets movies data from api, and user can add movies to their favorites
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  retrofit: ^4.0.1
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
